/**
 * Centralized Font Awesome icon mapping for the mobile app.
 *
 * Each key matches the AppSection type from utils/roles.ts.
 * Icons are sourced from the parent Arctic Wolves dashboard
 * sidebar navigation (dashboard.php).
 */

import {
  faHouse,
  faCalendarCheck,
  faCalendar,
  faUsers,
  faClipboardList,
  faFileLines,
  faClipboardCheck,
  faBullseye,
  faHeartPulse,
  faUtensils,
  faDumbbell,
  faVideo,
  faComments,
  faBell,
  faChartLine,
  faChartPie,
  faCashRegister,
  faStore,
  faMoneyCheckDollar,
  faUserGear,
  faUser,
  faChartBar,
  faUsersGear,
  faCheckCircle,
  faBars,
  faArrowLeft,
  faSpinner,
  faRotateRight,
  faSignOutAlt,
  faChevronRight,
  faEnvelope,
  faHockeyPuck,
  faClock,
  faLocationDot,
  faUserTie,
  faCalendarPlus,
  faCircleXmark,
  faChessBoard,
  faUserPlus,
  faLink,
  faLinkSlash,
  type IconDefinition,
} from '@fortawesome/free-solid-svg-icons';
import type { AppSection } from '../utils/roles';

/** Map of every navigable section to its Font Awesome icon */
export const sectionIcons: Record<AppSection, IconDefinition> = {
  home: faHouse,
  sessions: faCalendarCheck,
  schedule: faCalendar,
  athletes: faUsers,
  drills: faClipboardList,
  practicePlans: faFileLines,
  evaluations: faClipboardCheck,
  goals: faBullseye,
  health: faHeartPulse,
  nutrition: faUtensils,
  workouts: faDumbbell,
  video: faVideo,
  messages: faComments,
  notifications: faBell,
  reports: faChartLine,
  finance: faChartPie,
  pos: faCashRegister,
  shop: faStore,
  hr: faMoneyCheckDollar,
  admin: faUserGear,
  profile: faUser,
  stats: faChartBar,
  teamRoster: faUsersGear,
  campCheckin: faCheckCircle,
  gamePlan: faChessBoard,
};

export {
  faHouse,
  faCalendarCheck,
  faCalendar,
  faUsers,
  faClipboardList,
  faFileLines,
  faClipboardCheck,
  faBullseye,
  faHeartPulse,
  faUtensils,
  faDumbbell,
  faVideo,
  faComments,
  faBell,
  faChartLine,
  faChartPie,
  faCashRegister,
  faStore,
  faMoneyCheckDollar,
  faUserGear,
  faUser,
  faChartBar,
  faUsersGear,
  faCheckCircle,
  faBars,
  faArrowLeft,
  faSpinner,
  faRotateRight,
  faSignOutAlt,
  faChevronRight,
  faEnvelope,
  faHockeyPuck,
  faClock,
  faLocationDot,
  faUserTie,
  faCalendarPlus,
  faCircleXmark,
  faChessBoard,
  faUserPlus,
  faLink,
  faLinkSlash,
};

export type { IconDefinition };
